name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  frontend-push:
    name: Frontend - build & push
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: nircek/pikne-zadania-frontend

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  backend-push:
    name: Backend - build & push
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: nircek/pikne-zadania

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
